# Homework 10: Due Wednesday, April 16 at 11:59 PM

---

## <a name="HW1Inst">Instructions:</a>
---

1. <font color="tomato">Either click the COPY TO DRIVE button or use the menu File/Save/Save a Copy to save your own version of the notebook in your own folder in Google Drive.</font>

  - If you do not have a Google account, you will need to create a Google account in order to create your own individual copy of this notebook.
  - By default, the notebook will be saved in a folder named **Colab Notebooks** in your drive.
  - Feel free to name and store the notebook wherever you like!

2. <font color="mediumseagreen">After you have copied the notebook into your Drive, you can begin editing and saving your work.</font>

**Upload your completed assignment into Canvas as a Google Colab (or Jupyter) Notebook with file extension `.ipynb`.**

Upload your file into the Homework 10 assignment in Canvas before <font color="dodgerblue">**11:59PM on Wednesday, April 16.**</font>

**You must provide supporting work for your all of your answers.**

  - <font color="dodgerblue">That work will include using R code cells.</font>
    - **Feel free to insert as much R code as you like.**
    - You must interpret or explain how the output of a code cell is being utilized to solve the problem.
    - **Code with incomplete or missing explanations of why the output is useful may not receive full credit.**
  - <font color="dodgerblue">Your work will also involve writing explanations and justifications in text cells.</font>
    - **Be sure to type/write out the steps of your work/explanation so I can see how you arrived at your answer.**


## Important Academic Policies:
---

- **Be your own work.** Though you may collaborate with others, everyone is responsible for writing up the work in their own way using their own methods. Plagiarism of any form is not tolerated.
- **Be complete.** You must provide all work and/or explanations needed to find the solution. Answers with insufficient or incomplete supporting work may lose credit.
- **Adhere to the Code of Academic Honesty.**
- **Be clearly written (and legible if written).** Your solution to a problem must be clear, written in complete sentences. You may lose credit for work that is unclear or hard to follow.

## <font color="dodgerblue">Let me know if you need help, and **GOOD LUCK!!!**</font>

----

# <a name="Q1">Question 1</a>
---

Create each of the following matrices in R and be sure to print the output to the screen so the matrix is displayed on the screen.



## <a name="Q1a">Question 1a</a>

---

A matrix named $\mathbf{A}$ that has:

- First row has the values $2$, $9$, $11$, and $-5$ (in that order).
- Second row has the values $5$, $8$, $-1$, and $10$ (in that order).
- The last row has the values $-3$, $-8$, $12$, and $2$ (in that order).

Create the matrix using the `matrix()` function in R.


In [34]:
# create matrix A and display the output to screen

# Use matrix() to create a matrix, then in the first argument, input all the numbers inside this matrix, then use nrow to specify the number of rows,
# finally use byrow to tell the function to fill the first row with the first couple values until the row is filled, then move to the next row.
# And store the matrix in A.
A <- matrix(c(2, 9, 11, -5, 5, 8, -1, 10, -3, -8, 12, 2), nrow = 3, byrow = TRUE)

# Print out A to see its matrix.
print(A)

     [,1] [,2] [,3] [,4]
[1,]    2    9   11   -5
[2,]    5    8   -1   10
[3,]   -3   -8   12    2


## <a name="Q1b">Question 1b</a>

---

A matrix named $\mathbf{B}$ that has:

- First row has the values $1$, $0.9$, and $0.25$ (in that order).
- Second row has the values $2$, $0.3$, and $0.65$ (in that order).
- The third row has the values $3$, $0.1$, and $0.14$ (in that order).

Create the matrix by row or column binding vectors together with either the `cbind()` or `rbind()` functions. You may not use the `matrix()` function in R to create matrix $\mathbf{B}$.


In [35]:
# create matrix B and display the output to screen

# Create 3 vectors where each vector represents each row in the matrix.
vec1 <- c(1, 0.9, 0.25)
vec2 <- c(2, 0.3, 0.65)
vec3 <- c(3, 0.1, 0.14)

# Bind the 3 matrices using rbind which makes each vector becomes each row of this new matrix, and store it in B.
B <- rbind(vec1, vec2, vec3)

# Print out B to check its matrix.
print(B)

     [,1] [,2] [,3]
vec1    1  0.9 0.25
vec2    2  0.3 0.65
vec3    3  0.1 0.14


## <a name="Q1c">Question 1c</a>

---

A matrix named $\mathbf{C}$ that has:

- First row has the values $2$, $4$, $6$, and $8$ (in that order).
- Second row has the values $1$, $5$, $9$, and $13$ (in that order).
- The third row has the values $1$, $2$, $3$, and $4$ (in that order).

You may create matrix $\mathbf{C}$ using any method you like.

In [36]:
# create matrix C and display the output to screen

# I'll omit the detailed explanations of creating the matrix using matrix() because it's the same as in question 1a.

# Use matrix() to create the matrix and store it in C.
C <- matrix(c(2, 4, 6, 8, 1, 5, 9, 13, 1, 2, 3, 4), nrow = 3, byrow = TRUE)

# Print out C to check its matrix.
print(C)

     [,1] [,2] [,3] [,4]
[1,]    2    4    6    8
[2,]    1    5    9   13
[3,]    1    2    3    4


## <a name="Q1d">Question 1d</a>

---

A  matrix named $\mathbf{D}$ that is a column vector with:

- Value in row 1 is $0.2$.
- Value in row 2 is $-0.7$.
- Value in row 3 is $0.9$.
- Value in last row 4 is $0.5$.

Be sure you create a $4 \times 1$ matrix and not a one-dimensional vector. You may create matrix $\mathbf{D}$ using any method you like.

In [37]:
# create matrix D and display the output to screen

# Create a vector with the values specified in the question.
vecD <- c(0.2, -0.7, 0.9, 0.5)

# Use cbind() to make the vector a matrix and not a vector because cbind will put all the values from the vector in the same column. After that, store the result in D.
D <- cbind(vecD)

# Print D without using print() to show that it is still a matrix with the dimension of 4 x 1.
D

vecD
[1,]  0.2
[2,] -0.7
[3,]  0.9
[4,]  0.5

# <a name="Q2">Question 2</a>

---

Determine whether each operation exists or not.

- If the operation is defined, use a code cell below to compute it in R and be sure to display the output to the screen.
- If the operation is undefined, write a complete sentence to explain why not.

## <a name="Q2">Question 2a</a>

---

$5(\mathbf{A} + \mathbf{C})$

### <a name="sol2a">Solution to Question 2a</a>

---

Either insert a code cell to compute the given expression or in the space below explain (in a complete sentence) why the operation does not exist.






<br>  
<br>  

In [38]:
# Do the operation inside the parantheses first and store it in sum.
sum <- A + C

# then multiply sum by 5 and store it in result.
result <- 5 * sum

# Print out the result to check its matrix.
print(result)

     [,1] [,2] [,3] [,4]
[1,]   20   65   85   15
[2,]   30   65   40  115
[3,]  -10  -30   75   30


## <a name="Q2b">Question 2b</a>

---

$\mathbf{A} + \mathbf{B}$

### <a name="sol2b">Solution to Question 2b</a>

---

Either insert a code cell to compute the given expression or in the space below explain (in a complete sentence) why the operation does not exist.

This operation for this question doesn't exist because for matrices to perform addition operation, both of the matrices must have the same size. However, in this case, A has the size of 3 x 4 while B has the size of 3 x 3, which is not the same size. Therefore, the addition operation doesn't exist for this question.



<br>  
<br>  

## <a name="Q2c">Question 2c</a>

---

$\mathbf{B} \mathbf{A}$

### <a name="sol2c">Solution to Question 2c</a>

---

Either insert a code cell to compute the given expression or in the space below explain (in a complete sentence) why the operation does not exist.



<br>  
<br>  

In [39]:
# Perform matrix multiplication using %*% and multiply the matrix B and A and store it in product.
product <- B %*% A

# Print out the product to see its matrix.
print(product)

     [,1]  [,2]  [,3]   [,4]
vec1 5.75 14.20 13.10   4.50
vec2 3.55 15.20 29.50  -5.70
vec3 6.08 26.68 34.58 -13.72


## <a name="Q2d">Question 2d</a>

---

$\mathbf{A} \mathbf{C}$

### <a name="sol2d">Solution to Question 2d</a>

---

Either insert a code cell to compute the given expression or in the space below explain (in a complete sentence) why the operation does not exist.

This operation doesn't exist for this question because A and C has the wrong size for multplication operation. For matrices to be able to multiply each other, the columns of the first one has to match the rows of the second one. In this case, A has the size of 3 x 4, and C has the size of 3 x 4. The columns of A (which is 4) does not match with the rows of C (which is 3). Therefore, the multiplication operation for this question is not possible.



<br>  
<br>  

## <a name="Q2e">Question 2e</a>

---

$\mathbf{B} \mathbf{C} \mathbf{D}$

### <a name="sol2e">Solution to Question 2e</a>

---

Either insert a code cell to compute the given expression or in the space below explain (in a complete sentence) why the operation does not exist.


<br>  
<br>  

In [40]:
# Perform matrix multiplication between B, C, and D and store it in answer.
answer <- B %*% C %*% D

# Print out the answer to check its matrix.
print(answer)

       vecD
vec1 18.045
vec2 19.665
vec3 22.620


# <a name="Q3">Question 3</a>

---

Compute the following result: $(\mathbf{A}\mathbf{A}^T)^{-1}\mathbf{C}\mathbf{D}$.

In [41]:
# use code cell to compute the operations

# Perform the operation inside the parantheses first and store it in AAt. (t(A) is used to transpose matrix A because in the question A is required to be transpose and multiply with A)
AAt <- A %*% t(A)

# After the first operation, find its inverse using solve() and store it in AAt.inv.
AAt.inv <- solve(AAt)

# Perform the matrix multiplication between C and D and store it in CD.
CD <- C %*% D

# Finally, calculate the result by multiplying the AAt.inv and CD and store it in result1.
result1 <- AAt.inv %*% CD

# Print out result1 to check its matrix.
print(result1)

           vecD
[1,] 0.01718415
[2,] 0.07070192
[3,] 0.03513001


# <a name="Q4">Question 4</a>

---

Consider the following three matrices:

- $\mathbf{M}$ is a $5 \times 20$ matrix.
- $\mathbf{N}$ is a $20 \times 2$ matrix.
- $\mathbf{P}$ is a $2 \times 300$ matrix.


Is either of the following matrix algebra operations clearly faster?

<br>  

a. $\big( MN \big) P$

<br>

b. $M \big( NP \big)$

Support your answer with an justification using complete sentences.


## <a name="sol4">Solution to Question 4</a>

---

Support your answer with an justification using complete sentences.

The matrix algebra operations in a. should be faster than b, because the product of MN is a matrix with the dimension of 5 x 2 which is much smaller than the dimension of the product of NP which is 20 x 300. Therefore, computing MN would be faster than computing NP which resulting in computing a. faster than b.




<br>  
<br>  

# <a name="Q5">Question 5</a>

---

Use the `cbind()` function to bind matrices $\mathbf{A}$ and $\mathbf{B}$ together. Assign this result the name $\mathbf{E}$ and print the result to the screen.

In [42]:
# use code cell to answer

# Use cbind() to bind matrices together and store it in E.
# (cbind() when binding matrices, it just put the matrix in the latter argument (B) behind the matrix A and extends it)
E <- cbind(A, B)

# Print out E to check the matrix.
print(E)

     [,1] [,2] [,3] [,4] [,5] [,6] [,7]
vec1    2    9   11   -5    1  0.9 0.25
vec2    5    8   -1   10    2  0.3 0.65
vec3   -3   -8   12    2    3  0.1 0.14


# <a name="Q6">Question 6</a>

---

Use the `rbind` function to bind matrices $\mathbf{A}$ and $\mathbf{C}$ together. Assign this result the name $\mathbf{G}$ and print the result to the screen.

In [43]:
# use code cell to answer

# Use rbind() to bind matrix A and C and store it in G.
# (rbind() will stack the two matrices on top of each other and extends it where the first argument will be at the top and the latter argument will be at the bottom.)
G <- rbind(A, C)

# Print out G to check the matrix.
print(G)

     [,1] [,2] [,3] [,4]
[1,]    2    9   11   -5
[2,]    5    8   -1   10
[3,]   -3   -8   12    2
[4,]    2    4    6    8
[5,]    1    5    9   13
[6,]    1    2    3    4


# <a name="Q7">Question 7</a>

---

Select the following subset of $\mathbf{E}$: rows 2 and 3, and columns 4, 5 and 6. You do not need to store the result, but make sure it is printed on the screen.

In [44]:
# use code cell to answer

# Select the rows 2 and 3, and the columns from 4-6 of E using the slicing index.
E[2:3, 4:6]

[,1] [,2] [,3]
vec2 10   2    0.3 
vec3  2   3    0.1

# <a name="Q8">Question 8</a>

---

Subset row 1 of $\mathbf{E}$. Do not let the result be coerced to a `vector`. Rather make sure it is returned as a `matrix` object. You do not need to store the result, but make sure it is printed on the screen.


In [45]:
# use code cell to answer

# Select the 1st row of E using the slicing index,
# and have drop = FALSE to make sure that the result will be a matrix object and not a vector object.
E[1, ,drop = FALSE]

[,1] [,2] [,3] [,4] [,5] [,6] [,7]
vec1 2    9    11   -5   1    0.9  0.25

# <a name="Q9">Question 9</a>

---


Subset the following 3 elements from $\mathbf{E}$ using at most 2 commands:

- The $(1, 1)$ element in the first row and first colmn.
- The $(3, 2)$ element in row 3 and column 2.
- The $(2, 6)$ element in row 2 and column 6.

You do not need to store the result, but make sure it is printed on the screen. Answers obtained using more than 2 commands will not earn credit.

In [46]:
# use code cell to enter at most 2 commands

# Create a matrix that stores the position of each element where the first row stores 1 1, second row stores 3 2, and the third row stores 2 6.
# And store this matrix in pos. (this matrix is created the same way as in question 1a)
pos <- matrix(c(1, 1, 3, 2, 2, 6), nrow = 3, byrow = TRUE)

# Find each element by using E[pos] which will subset the matrix E and find each element from the position given in the pos matrix.
E[pos]

[1]  2.0 -8.0  0.3

# <a name="Q10">Question 10</a>

---

Create arrays $\mathbf{H}$ and $\mathbf{J}$ described in each part.


## <a name="Q10a">Question 10a</a>

---

Create a $2 \times 2 \times 3$ array with all 1's in the 1st slice (of the 3rd dimension), all 2's in the 2nd slice (of the 3rd dimension), all 3's in the 3rd slice (of the 3rd dimension). Assign this object the name $\mathbf{H}$ and print the result to the screen **displayed as an array**.




In [47]:
# Install the packages abind to utilize abind for array binding.
install.packages("abind")
library(abind)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)



In [48]:
# use code cell to answer

# Create 3 matrices that is each "slice" in the array where slice1 is the 1st slice, slice2 is the 2nd slice, and slice3 is the 3rd slice.
# Each slice is a 2 x 2 matrix, this is from the question's saying to create a 2 x 2 x 3 array which means to create 3 matrices that are 2 x 2,
# and stack it on top of each other.
slice1 <- matrix(c(1, 1, 1, 1), nrow = 2, byrow = TRUE)
slice2 <- matrix(c(2, 2, 2, 2), nrow = 2, byrow = TRUE)
slice3 <- matrix(c(3, 3, 3, 3), nrow = 2, byrow = TRUE)

# Bind these matrices using abind to create an array with these slices, and specify along = 3 to tell the abind function-
# to bind these matrices in the third dimension. And store the result in H.
H <- abind(slice1, slice2, slice3, along = 3)

# Print out H to check its array.
print(H)

, , 1

     [,1] [,2]
[1,]    1    1
[2,]    1    1

, , 2

     [,1] [,2]
[1,]    2    2
[2,]    2    2

, , 3

     [,1] [,2]
[1,]    3    3
[2,]    3    3



In [49]:
# This is another way of creating the same array without using abind.

# Put all the numbers that are needed for each slice in the first argument, and specify the-
# dimensions of the array using dim.
test <- array(c(1,1,1,1,2,2,2,2,3,3,3,3), dim = c(2, 2, 3))

# Print out the array to see if its the same as the H array.
print(test)

, , 1

     [,1] [,2]
[1,]    1    1
[2,]    1    1

, , 2

     [,1] [,2]
[1,]    2    2
[2,]    2    2

, , 3

     [,1] [,2]
[1,]    3    3
[2,]    3    3



## <a name="Q10b">Question 10b</a>

---

Create a $3 \times 2 \times 3$ array with all 4's in the 1st slice (of the 3rd dimension), all 5's in the 2nd slice (of the 3rd dimension), all 6's in the 3rd slice (of the 3rd dimension). Assign this object the name $\mathbf{J}$ and print the result to the screen **displayed as an array**.

In [50]:
# use code cell to answer

# This is the same procedure as in question 10a, so I will omit the detailed explanations.

# Create 3 x 2 matrices to combine for the array.
all4s <- matrix(c(4, 4, 4, 4, 4, 4), nrow = 3, byrow = TRUE)
all5s <- matrix(c(5, 5, 5, 5, 5, 5), nrow = 3, byrow = TRUE)
all6s <- matrix(c(6, 6, 6, 6, 6, 6), nrow = 3, byrow = TRUE)

# Bind the matrices in the 3rd dimension to create the array and store it in J.
J <- abind(all4s, all5s, all6s, along = 3)

# Print out J to check the array.
print(J)

, , 1

     [,1] [,2]
[1,]    4    4
[2,]    4    4
[3,]    4    4

, , 2

     [,1] [,2]
[1,]    5    5
[2,]    5    5
[3,]    5    5

, , 3

     [,1] [,2]
[1,]    6    6
[2,]    6    6
[3,]    6    6



# <a name="Q11">Question 11</a>

---


Can we bind $\mathbf{H}$ and $\mathbf{J}$ along the 3rd dimension of the arrays?


- If so, use a code cell to bind the two arrays along the 3rd dimension and print the result to the screen **displayed as an array**.
  - You do not need to store this array (if it exists).
- If not, write a complete sentence to explain why not.

You may need to load and install a package to help (if the two arrays can be bound together).


## <a name="sol11a">Solution to Question 11</a>

---

Either insert a code cell to bind the arrays or in the space below explain (in a complete sentence) why the arrays cannot be bound along the 3rd dimension.


For the arrays to be bounded along the 3rd dimension, each matrices in the array of both arrays must match. In this case, the array H has 2x2 matrices stacking on top of each other 3 times where the array J has 3x2 matrices stacking on top of each other 3 times. You can see that the array H has 2x2 matrices while the array J has 3x2 matrices. Since, the size of the matrices in the array doesn't match, it is not possible to bind H and J along the 3rd dimension of the arrays.



<br>  
<br>  

# <a name="Q12">Question 12</a>

---

Create a new array, $\mathbf{K}$, by binding $\mathbf{H}$ and $\mathbf{J}$ along their first dimension. Print the result to the screen **displayed as an array**. In the solution space below, enter the size of the new array.

If you have not already done so, you may need to load and install a package to help.



## <a name="sol12">Solution to Question 12</a>

---

<mark>Enter the dimension of $\mathbf{K}$ in the space below.</mark>

<br>  

$\mathbf{K}$ has dimension $5 \times 2 \times 3$.


<br>  
<br>  

In [51]:
# use code cell to create the array

# Bind the arrays H and J along the first dimension using abind() and make sure the along argument is equal to 1.
# Doing abind in the first dimension is similar to doing rbind to every matrix slices where H is the first argument and J is the latter argument.
K <- abind(H, J, along = 1)

# Print out K to check the array.
print(K)

, , 1

     [,1] [,2]
[1,]    1    1
[2,]    1    1
[3,]    4    4
[4,]    4    4
[5,]    4    4

, , 2

     [,1] [,2]
[1,]    2    2
[2,]    2    2
[3,]    5    5
[4,]    5    5
[5,]    5    5

, , 3

     [,1] [,2]
[1,]    3    3
[2,]    3    3
[3,]    6    6
[4,]    6    6
[5,]    6    6



# <a name="Q13">Question 13</a>

---


Select the following subset of $\mathbf{K}$ and print the result to the screen:

- Rows 2 and 3 (of the first dimension),
- Column 1 (of the second dimension)
- Slices 2 and 3 (of the third dimension).

Ensure that the result remains an `array` and is not coerced to a `matrix`. You do not need to store the result, but **make sure it is displayed as an array on screen**.

In [52]:
# use code cell to answer

# Subset all the values using slicing index, and make sure drop = FALSE to make sure that the result is still an array object.
# The array has 3 dimensions, so there are 3 arguments for the slicing index. The first argument is rows, second is columns, and third is dimensions.
subset1 <- K[2:3, ,1, drop = FALSE]
subset2 <- K[, 1, 2, drop = FALSE]
subset3 <- K[, , 2:3, drop = FALSE]

In [53]:
# Print out the first subset.
# (The , , 1 on top left of every subset shows that this is still an array object.)
print(subset1)

, , 1

     [,1] [,2]
[1,]    1    1
[2,]    4    4



In [54]:
# Print out the second subset.
print(subset2)

, , 1

     [,1]
[1,]    2
[2,]    2
[3,]    5
[4,]    5
[5,]    5



In [55]:
# Print out the third subset.
print(subset3)

, , 1

     [,1] [,2]
[1,]    2    2
[2,]    2    2
[3,]    5    5
[4,]    5    5
[5,]    5    5

, , 2

     [,1] [,2]
[1,]    3    3
[2,]    3    3
[3,]    6    6
[4,]    6    6
[5,]    6    6



# <a name="Q14">Question 14</a>

---

Create a `list` object named $\mathbf{L}$ with the following three elements (in the given order):

- First element is matrix $\mathbf{A}$ (created in [Question 1a](#Q1a)).
- Second element is array $\mathbf{H}$ (created in [Question 10a](#Q10a)).
- Third element is a vector containing the following three characters (in the given order),  "a", "b", and "c".

Print the result to the screen.


In [56]:
# use code cell to answer

# Create a list using list() and store the values as specified from the question, and store it in L.
L <- list(A, H, c("a","b","c"))

# Print out L to check the list.
print(L)

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    2    9   11   -5
[2,]    5    8   -1   10
[3,]   -3   -8   12    2

[[2]]
, , 1

     [,1] [,2]
[1,]    1    1
[2,]    1    1

, , 2

     [,1] [,2]
[1,]    2    2
[2,]    2    2

, , 3

     [,1] [,2]
[1,]    3    3
[2,]    3    3


[[3]]
[1] "a" "b" "c"



# <a name="Q15">Question 15</a>

---

Subset elements 1 and 3 from list $\mathbf{L}$. You do not need to store the result, but make sure the output is printed to the screen.

In [57]:
# use code cell to answer

# Use slicing index to subset the elements 1 and 3 from the list L.
L[c(1,3)]

[[1]]
     [,1] [,2] [,3] [,4]
[1,]    2    9   11   -5
[2,]    5    8   -1   10
[3,]   -3   -8   12    2

[[2]]
[1] "a" "b" "c"

# <a name="Q16">Question 16</a>

---

Extract the 3rd element out from list $\mathbf{L}$. Note, we want to actually **pull this element out of** $\mathbf{L}$, not simply subset $\mathbf{L}$.


In [58]:
# use code cell to answer

# To "extract" the elements use two brackets and the index number of the element you want to extract.
# This is different from subsetting because we get the values directly from the list, rather than just displaying the subsetted values.
L[[3]]

[1] "a" "b" "c"

# <a name="save2">Be Sure You Have Saved Your Work!</a>

---

This notebook is a shared Colab notebook available for anyone to view. However, since everyone is sharing this notebook, you do not have permission to save changes to this shared Colab notebook. In order to save your work:

1. You will need to set up a free Google Drive account. If you already have a Google Drive account, you are ready to go!
2. Click the `Copy to Drive` button to the right of the `+ Code` and `+ Text` buttons on top of the notebook.
3. Select from the menu `File/Save a Copy in Drive`.
  - By default, the notebook will be saved in a folder named **Colab Notebooks** in your Drive.
  - Feel free to rename and store the notebook wherever you like.
